spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    response-type: code
    grant-type: authorization_code
    scope: email

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_token_expiration: ${ACCESS_TOKEN_EXPIRATION}
